---
title: "Presentation"
author: "Peter Xiong"
date: "2024-12-03"
output: html_document
---

### Our goal of this program

Image Classification is a type of supervised machine learning, model is trained using labeled data and known outputs, whose goal is to be able to recognize and classify images into their respective class based on features gathered from said images. For our vignette we focus on multi-class classification using a convolutional neural network, a model type designed for spatial data such as images, so using a model to classify images into one of multiple categories.

Our example data involves the case of brain tumors, there are many different types of brain tumors with over 120 being categorized by location and cell formation. Thus, diagnosing brain tumors is often challenging and requires extensive imaging tests and scans which often leads to delays in diagnosis. Using machine learning can combat this issue, specifically image classification to classify MRI scans of brain tumors into diagnosis categories.

Overall, our model achieved.

### Dataset


### Preprosessing


### Model


### Conclusion
